//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzePay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arrear
    {
        public int ArrearId { get; set; }
        public int UserId { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public double Amount { get; set; }
        public int Deleted { get; set; }
        public string Description { get; set; }
    }
}
